//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangmanGame.Client.UserServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserServiceReference.IUserService")]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/LoadProfile", ReplyAction="http://tempuri.org/IUserService/LoadProfileResponse")]
        HangmanGame.Core.Core.DTOs.ProfileResponseDto LoadProfile(HangmanGame.Core.Core.DTOs.LoadProfileRequestDto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/LoadProfile", ReplyAction="http://tempuri.org/IUserService/LoadProfileResponse")]
        System.Threading.Tasks.Task<HangmanGame.Core.Core.DTOs.ProfileResponseDto> LoadProfileAsync(HangmanGame.Core.Core.DTOs.LoadProfileRequestDto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/SearchUsers", ReplyAction="http://tempuri.org/IUserService/SearchUsersResponse")]
        HangmanGame.Core.Core.DTOs.UserCardResponseDto SearchUsers(HangmanGame.Core.Core.DTOs.UserCardRequestDto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/SearchUsers", ReplyAction="http://tempuri.org/IUserService/SearchUsersResponse")]
        System.Threading.Tasks.Task<HangmanGame.Core.Core.DTOs.UserCardResponseDto> SearchUsersAsync(HangmanGame.Core.Core.DTOs.UserCardRequestDto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UpdateProfile", ReplyAction="http://tempuri.org/IUserService/UpdateProfileResponse")]
        HangmanGame.Core.Core.DTOs.UpdateProfileResponseDto UpdateProfile(HangmanGame.Core.Core.DTOs.UpdateProfileRequestDto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UpdateProfile", ReplyAction="http://tempuri.org/IUserService/UpdateProfileResponse")]
        System.Threading.Tasks.Task<HangmanGame.Core.Core.DTOs.UpdateProfileResponseDto> UpdateProfileAsync(HangmanGame.Core.Core.DTOs.UpdateProfileRequestDto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetScoreBreakdown", ReplyAction="http://tempuri.org/IUserService/GetScoreBreakdownResponse")]
        HangmanGame.Core.Core.DTOs.GetScoreBreakdownResponseDto GetScoreBreakdown(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetScoreBreakdown", ReplyAction="http://tempuri.org/IUserService/GetScoreBreakdownResponse")]
        System.Threading.Tasks.Task<HangmanGame.Core.Core.DTOs.GetScoreBreakdownResponseDto> GetScoreBreakdownAsync(int userId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : HangmanGame.Client.UserServiceReference.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<HangmanGame.Client.UserServiceReference.IUserService>, HangmanGame.Client.UserServiceReference.IUserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HangmanGame.Core.Core.DTOs.ProfileResponseDto LoadProfile(HangmanGame.Core.Core.DTOs.LoadProfileRequestDto request) {
            return base.Channel.LoadProfile(request);
        }
        
        public System.Threading.Tasks.Task<HangmanGame.Core.Core.DTOs.ProfileResponseDto> LoadProfileAsync(HangmanGame.Core.Core.DTOs.LoadProfileRequestDto request) {
            return base.Channel.LoadProfileAsync(request);
        }
        
        public HangmanGame.Core.Core.DTOs.UserCardResponseDto SearchUsers(HangmanGame.Core.Core.DTOs.UserCardRequestDto request) {
            return base.Channel.SearchUsers(request);
        }
        
        public System.Threading.Tasks.Task<HangmanGame.Core.Core.DTOs.UserCardResponseDto> SearchUsersAsync(HangmanGame.Core.Core.DTOs.UserCardRequestDto request) {
            return base.Channel.SearchUsersAsync(request);
        }
        
        public HangmanGame.Core.Core.DTOs.UpdateProfileResponseDto UpdateProfile(HangmanGame.Core.Core.DTOs.UpdateProfileRequestDto request) {
            return base.Channel.UpdateProfile(request);
        }
        
        public System.Threading.Tasks.Task<HangmanGame.Core.Core.DTOs.UpdateProfileResponseDto> UpdateProfileAsync(HangmanGame.Core.Core.DTOs.UpdateProfileRequestDto request) {
            return base.Channel.UpdateProfileAsync(request);
        }
        
        public HangmanGame.Core.Core.DTOs.GetScoreBreakdownResponseDto GetScoreBreakdown(int userId) {
            return base.Channel.GetScoreBreakdown(userId);
        }
        
        public System.Threading.Tasks.Task<HangmanGame.Core.Core.DTOs.GetScoreBreakdownResponseDto> GetScoreBreakdownAsync(int userId) {
            return base.Channel.GetScoreBreakdownAsync(userId);
        }
    }
}
