//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangmanGame.Client.MatchServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MatchServiceReference.IMatchService")]
    public interface IMatchService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/GetAvailableMatches", ReplyAction="http://tempuri.org/IMatchService/GetAvailableMatchesResponse")]
        HangmanGame.Core.Core.DTOs.GetAvailableMatchesResponseDto GetAvailableMatches(HangmanGame.Core.Core.DTOs.GetAvailableMatchesRequestDto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/GetAvailableMatches", ReplyAction="http://tempuri.org/IMatchService/GetAvailableMatchesResponse")]
        System.Threading.Tasks.Task<HangmanGame.Core.Core.DTOs.GetAvailableMatchesResponseDto> GetAvailableMatchesAsync(HangmanGame.Core.Core.DTOs.GetAvailableMatchesRequestDto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/GetMatchById", ReplyAction="http://tempuri.org/IMatchService/GetMatchByIdResponse")]
        HangmanGame.Core.Core.DTOs.GetMatchDetailsResponseDto GetMatchById(HangmanGame.Core.Core.DTOs.GetMatchDetailsRequestDto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/GetMatchById", ReplyAction="http://tempuri.org/IMatchService/GetMatchByIdResponse")]
        System.Threading.Tasks.Task<HangmanGame.Core.Core.DTOs.GetMatchDetailsResponseDto> GetMatchByIdAsync(HangmanGame.Core.Core.DTOs.GetMatchDetailsRequestDto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/CreateMatch", ReplyAction="http://tempuri.org/IMatchService/CreateMatchResponse")]
        HangmanGame.Core.Core.DTOs.CreateMatchResponseDto CreateMatch(HangmanGame.Core.Core.DTOs.CreateMatchRequestDto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/CreateMatch", ReplyAction="http://tempuri.org/IMatchService/CreateMatchResponse")]
        System.Threading.Tasks.Task<HangmanGame.Core.Core.DTOs.CreateMatchResponseDto> CreateMatchAsync(HangmanGame.Core.Core.DTOs.CreateMatchRequestDto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/JoinMatch", ReplyAction="http://tempuri.org/IMatchService/JoinMatchResponse")]
        HangmanGame.Core.Core.DTOs.JoinMatchResponseDto JoinMatch(HangmanGame.Core.Core.DTOs.JoinMatchRequestDto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/JoinMatch", ReplyAction="http://tempuri.org/IMatchService/JoinMatchResponse")]
        System.Threading.Tasks.Task<HangmanGame.Core.Core.DTOs.JoinMatchResponseDto> JoinMatchAsync(HangmanGame.Core.Core.DTOs.JoinMatchRequestDto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/StartMatch", ReplyAction="http://tempuri.org/IMatchService/StartMatchResponse")]
        HangmanGame.Core.Core.DTOs.StartMatchResponseDto StartMatch(HangmanGame.Core.Core.DTOs.StartMatchRequestDto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/StartMatch", ReplyAction="http://tempuri.org/IMatchService/StartMatchResponse")]
        System.Threading.Tasks.Task<HangmanGame.Core.Core.DTOs.StartMatchResponseDto> StartMatchAsync(HangmanGame.Core.Core.DTOs.StartMatchRequestDto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/UpdateMatchWord", ReplyAction="http://tempuri.org/IMatchService/UpdateMatchWordResponse")]
        HangmanGame.Core.Core.DTOs.UpdateMatchWordResponseDto UpdateMatchWord(HangmanGame.Core.Core.DTOs.UpdateMatchWordRequestDto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/UpdateMatchWord", ReplyAction="http://tempuri.org/IMatchService/UpdateMatchWordResponse")]
        System.Threading.Tasks.Task<HangmanGame.Core.Core.DTOs.UpdateMatchWordResponseDto> UpdateMatchWordAsync(HangmanGame.Core.Core.DTOs.UpdateMatchWordRequestDto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/CancelMatch", ReplyAction="http://tempuri.org/IMatchService/CancelMatchResponse")]
        HangmanGame.Core.Core.DTOs.CancelMatchResponseDto CancelMatch(HangmanGame.Core.Core.DTOs.CancelMatchRequestDto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/CancelMatch", ReplyAction="http://tempuri.org/IMatchService/CancelMatchResponse")]
        System.Threading.Tasks.Task<HangmanGame.Core.Core.DTOs.CancelMatchResponseDto> CancelMatchAsync(HangmanGame.Core.Core.DTOs.CancelMatchRequestDto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/GetLiveGameLoopState", ReplyAction="http://tempuri.org/IMatchService/GetLiveGameLoopStateResponse")]
        HangmanGame.Core.Core.Interfaces.Services.LiveGameRuntimeState GetLiveGameLoopState(int matchId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/GetLiveGameLoopState", ReplyAction="http://tempuri.org/IMatchService/GetLiveGameLoopStateResponse")]
        System.Threading.Tasks.Task<HangmanGame.Core.Core.Interfaces.Services.LiveGameRuntimeState> GetLiveGameLoopStateAsync(int matchId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/SubmitGuesserLetter", ReplyAction="http://tempuri.org/IMatchService/SubmitGuesserLetterResponse")]
        void SubmitGuesserLetter(int matchId, char letter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/SubmitGuesserLetter", ReplyAction="http://tempuri.org/IMatchService/SubmitGuesserLetterResponse")]
        System.Threading.Tasks.Task SubmitGuesserLetterAsync(int matchId, char letter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/SubmitHostValidation", ReplyAction="http://tempuri.org/IMatchService/SubmitHostValidationResponse")]
        bool SubmitHostValidation(int matchId, bool isCorrect);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/SubmitHostValidation", ReplyAction="http://tempuri.org/IMatchService/SubmitHostValidationResponse")]
        System.Threading.Tasks.Task<bool> SubmitHostValidationAsync(int matchId, bool isCorrect);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMatchServiceChannel : HangmanGame.Client.MatchServiceReference.IMatchService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MatchServiceClient : System.ServiceModel.ClientBase<HangmanGame.Client.MatchServiceReference.IMatchService>, HangmanGame.Client.MatchServiceReference.IMatchService {
        
        public MatchServiceClient() {
        }
        
        public MatchServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MatchServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MatchServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MatchServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HangmanGame.Core.Core.DTOs.GetAvailableMatchesResponseDto GetAvailableMatches(HangmanGame.Core.Core.DTOs.GetAvailableMatchesRequestDto request) {
            return base.Channel.GetAvailableMatches(request);
        }
        
        public System.Threading.Tasks.Task<HangmanGame.Core.Core.DTOs.GetAvailableMatchesResponseDto> GetAvailableMatchesAsync(HangmanGame.Core.Core.DTOs.GetAvailableMatchesRequestDto request) {
            return base.Channel.GetAvailableMatchesAsync(request);
        }
        
        public HangmanGame.Core.Core.DTOs.GetMatchDetailsResponseDto GetMatchById(HangmanGame.Core.Core.DTOs.GetMatchDetailsRequestDto request) {
            return base.Channel.GetMatchById(request);
        }
        
        public System.Threading.Tasks.Task<HangmanGame.Core.Core.DTOs.GetMatchDetailsResponseDto> GetMatchByIdAsync(HangmanGame.Core.Core.DTOs.GetMatchDetailsRequestDto request) {
            return base.Channel.GetMatchByIdAsync(request);
        }
        
        public HangmanGame.Core.Core.DTOs.CreateMatchResponseDto CreateMatch(HangmanGame.Core.Core.DTOs.CreateMatchRequestDto request) {
            return base.Channel.CreateMatch(request);
        }
        
        public System.Threading.Tasks.Task<HangmanGame.Core.Core.DTOs.CreateMatchResponseDto> CreateMatchAsync(HangmanGame.Core.Core.DTOs.CreateMatchRequestDto request) {
            return base.Channel.CreateMatchAsync(request);
        }
        
        public HangmanGame.Core.Core.DTOs.JoinMatchResponseDto JoinMatch(HangmanGame.Core.Core.DTOs.JoinMatchRequestDto request) {
            return base.Channel.JoinMatch(request);
        }
        
        public System.Threading.Tasks.Task<HangmanGame.Core.Core.DTOs.JoinMatchResponseDto> JoinMatchAsync(HangmanGame.Core.Core.DTOs.JoinMatchRequestDto request) {
            return base.Channel.JoinMatchAsync(request);
        }
        
        public HangmanGame.Core.Core.DTOs.StartMatchResponseDto StartMatch(HangmanGame.Core.Core.DTOs.StartMatchRequestDto request) {
            return base.Channel.StartMatch(request);
        }
        
        public System.Threading.Tasks.Task<HangmanGame.Core.Core.DTOs.StartMatchResponseDto> StartMatchAsync(HangmanGame.Core.Core.DTOs.StartMatchRequestDto request) {
            return base.Channel.StartMatchAsync(request);
        }
        
        public HangmanGame.Core.Core.DTOs.UpdateMatchWordResponseDto UpdateMatchWord(HangmanGame.Core.Core.DTOs.UpdateMatchWordRequestDto request) {
            return base.Channel.UpdateMatchWord(request);
        }
        
        public System.Threading.Tasks.Task<HangmanGame.Core.Core.DTOs.UpdateMatchWordResponseDto> UpdateMatchWordAsync(HangmanGame.Core.Core.DTOs.UpdateMatchWordRequestDto request) {
            return base.Channel.UpdateMatchWordAsync(request);
        }
        
        public HangmanGame.Core.Core.DTOs.CancelMatchResponseDto CancelMatch(HangmanGame.Core.Core.DTOs.CancelMatchRequestDto request) {
            return base.Channel.CancelMatch(request);
        }
        
        public System.Threading.Tasks.Task<HangmanGame.Core.Core.DTOs.CancelMatchResponseDto> CancelMatchAsync(HangmanGame.Core.Core.DTOs.CancelMatchRequestDto request) {
            return base.Channel.CancelMatchAsync(request);
        }
        
        public HangmanGame.Core.Core.Interfaces.Services.LiveGameRuntimeState GetLiveGameLoopState(int matchId) {
            return base.Channel.GetLiveGameLoopState(matchId);
        }
        
        public System.Threading.Tasks.Task<HangmanGame.Core.Core.Interfaces.Services.LiveGameRuntimeState> GetLiveGameLoopStateAsync(int matchId) {
            return base.Channel.GetLiveGameLoopStateAsync(matchId);
        }
        
        public void SubmitGuesserLetter(int matchId, char letter) {
            base.Channel.SubmitGuesserLetter(matchId, letter);
        }
        
        public System.Threading.Tasks.Task SubmitGuesserLetterAsync(int matchId, char letter) {
            return base.Channel.SubmitGuesserLetterAsync(matchId, letter);
        }
        
        public bool SubmitHostValidation(int matchId, bool isCorrect) {
            return base.Channel.SubmitHostValidation(matchId, isCorrect);
        }
        
        public System.Threading.Tasks.Task<bool> SubmitHostValidationAsync(int matchId, bool isCorrect) {
            return base.Channel.SubmitHostValidationAsync(matchId, isCorrect);
        }
    }
}
