//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangmanGame.Client.MatchServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MatchServiceReference.IMatchService")]
    public interface IMatchService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/GetAvailableMatches", ReplyAction="http://tempuri.org/IMatchService/GetAvailableMatchesResponse")]
        HangmanGame.Core.Core.DTOs.GetAvailableMatchesResponseDto GetAvailableMatches(HangmanGame.Core.Core.DTOs.GetAvailableMatchesRequestDto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/GetAvailableMatches", ReplyAction="http://tempuri.org/IMatchService/GetAvailableMatchesResponse")]
        System.Threading.Tasks.Task<HangmanGame.Core.Core.DTOs.GetAvailableMatchesResponseDto> GetAvailableMatchesAsync(HangmanGame.Core.Core.DTOs.GetAvailableMatchesRequestDto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/GetMatchById", ReplyAction="http://tempuri.org/IMatchService/GetMatchByIdResponse")]
        HangmanGame.Core.Core.DTOs.GetMatchDetailsResponseDto GetMatchById(HangmanGame.Core.Core.DTOs.GetMatchDetailsRequestDto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/GetMatchById", ReplyAction="http://tempuri.org/IMatchService/GetMatchByIdResponse")]
        System.Threading.Tasks.Task<HangmanGame.Core.Core.DTOs.GetMatchDetailsResponseDto> GetMatchByIdAsync(HangmanGame.Core.Core.DTOs.GetMatchDetailsRequestDto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/CreateMatch", ReplyAction="http://tempuri.org/IMatchService/CreateMatchResponse")]
        HangmanGame.Core.Core.DTOs.CreateMatchResponseDto CreateMatch(HangmanGame.Core.Core.DTOs.CreateMatchRequestDto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/CreateMatch", ReplyAction="http://tempuri.org/IMatchService/CreateMatchResponse")]
        System.Threading.Tasks.Task<HangmanGame.Core.Core.DTOs.CreateMatchResponseDto> CreateMatchAsync(HangmanGame.Core.Core.DTOs.CreateMatchRequestDto request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMatchServiceChannel : HangmanGame.Client.MatchServiceReference.IMatchService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MatchServiceClient : System.ServiceModel.ClientBase<HangmanGame.Client.MatchServiceReference.IMatchService>, HangmanGame.Client.MatchServiceReference.IMatchService {
        
        public MatchServiceClient() {
        }
        
        public MatchServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MatchServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MatchServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MatchServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HangmanGame.Core.Core.DTOs.GetAvailableMatchesResponseDto GetAvailableMatches(HangmanGame.Core.Core.DTOs.GetAvailableMatchesRequestDto request) {
            return base.Channel.GetAvailableMatches(request);
        }
        
        public System.Threading.Tasks.Task<HangmanGame.Core.Core.DTOs.GetAvailableMatchesResponseDto> GetAvailableMatchesAsync(HangmanGame.Core.Core.DTOs.GetAvailableMatchesRequestDto request) {
            return base.Channel.GetAvailableMatchesAsync(request);
        }
        
        public HangmanGame.Core.Core.DTOs.GetMatchDetailsResponseDto GetMatchById(HangmanGame.Core.Core.DTOs.GetMatchDetailsRequestDto request) {
            return base.Channel.GetMatchById(request);
        }
        
        public System.Threading.Tasks.Task<HangmanGame.Core.Core.DTOs.GetMatchDetailsResponseDto> GetMatchByIdAsync(HangmanGame.Core.Core.DTOs.GetMatchDetailsRequestDto request) {
            return base.Channel.GetMatchByIdAsync(request);
        }
        
        public HangmanGame.Core.Core.DTOs.CreateMatchResponseDto CreateMatch(HangmanGame.Core.Core.DTOs.CreateMatchRequestDto request) {
            return base.Channel.CreateMatch(request);
        }
        
        public System.Threading.Tasks.Task<HangmanGame.Core.Core.DTOs.CreateMatchResponseDto> CreateMatchAsync(HangmanGame.Core.Core.DTOs.CreateMatchRequestDto request) {
            return base.Channel.CreateMatchAsync(request);
        }
    }
}
