//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangmanGame.Client.WordServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WordServiceReference.IWordService")]
    public interface IWordService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordService/GetWords", ReplyAction="http://tempuri.org/IWordService/GetWordsResponse")]
        HangmanGame.Core.Core.DTOs.WordResponseDto GetWords(HangmanGame.Core.Core.DTOs.WordRequestDto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordService/GetWords", ReplyAction="http://tempuri.org/IWordService/GetWordsResponse")]
        System.Threading.Tasks.Task<HangmanGame.Core.Core.DTOs.WordResponseDto> GetWordsAsync(HangmanGame.Core.Core.DTOs.WordRequestDto request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWordServiceChannel : HangmanGame.Client.WordServiceReference.IWordService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WordServiceClient : System.ServiceModel.ClientBase<HangmanGame.Client.WordServiceReference.IWordService>, HangmanGame.Client.WordServiceReference.IWordService {
        
        public WordServiceClient() {
        }
        
        public WordServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WordServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WordServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WordServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HangmanGame.Core.Core.DTOs.WordResponseDto GetWords(HangmanGame.Core.Core.DTOs.WordRequestDto request) {
            return base.Channel.GetWords(request);
        }
        
        public System.Threading.Tasks.Task<HangmanGame.Core.Core.DTOs.WordResponseDto> GetWordsAsync(HangmanGame.Core.Core.DTOs.WordRequestDto request) {
            return base.Channel.GetWordsAsync(request);
        }
    }
}
