//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangmanGame.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HangmanGame.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You won’t be penalized.
        /// </summary>
        public static string Append_noPenalization {
            get {
                return ResourceManager.GetString("Append_noPenalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your score hasn’t been affected.
        /// </summary>
        public static string Append_noPointsLost {
            get {
                return ResourceManager.GetString("Append_noPointsLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You’ll lose 3 points if you leave now.
        /// </summary>
        public static string Append_penalization {
            get {
                return ResourceManager.GetString("Append_penalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You’ve lost 3 points.
        /// </summary>
        public static string Append_pointsLost {
            get {
                return ResourceManager.GetString("Append_pointsLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Button_accept {
            get {
                return ResourceManager.GetString("Button_accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already registered?.
        /// </summary>
        public static string Button_alreadyRegistered {
            get {
                return ResourceManager.GetString("Button_alreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_cancel {
            get {
                return ResourceManager.GetString("Button_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Button_confirm {
            get {
                return ResourceManager.GetString("Button_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Button_continue {
            get {
                return ResourceManager.GetString("Button_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct.
        /// </summary>
        public static string Button_correctGuess {
            get {
                return ResourceManager.GetString("Button_correctGuess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Button_create {
            get {
                return ResourceManager.GetString("Button_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create match.
        /// </summary>
        public static string Button_createMatch {
            get {
                return ResourceManager.GetString("Button_createMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete account.
        /// </summary>
        public static string Button_deleteAccount {
            get {
                return ResourceManager.GetString("Button_deleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify profile.
        /// </summary>
        public static string Button_editProfile {
            get {
                return ResourceManager.GetString("Button_editProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Button_exit {
            get {
                return ResourceManager.GetString("Button_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password.
        /// </summary>
        public static string Button_forgotPassword {
            get {
                return ResourceManager.GetString("Button_forgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        public static string Button_goBack {
            get {
                return ResourceManager.GetString("Button_goBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide details.
        /// </summary>
        public static string Button_hideDetails {
            get {
                return ResourceManager.GetString("Button_hideDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect.
        /// </summary>
        public static string Button_incorrectGuess {
            get {
                return ResourceManager.GetString("Button_incorrectGuess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join match.
        /// </summary>
        public static string Button_joinMatch {
            get {
                return ResourceManager.GetString("Button_joinMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kick player.
        /// </summary>
        public static string Button_kickPlayer {
            get {
                return ResourceManager.GetString("Button_kickPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave match.
        /// </summary>
        public static string Button_leaveMatch {
            get {
                return ResourceManager.GetString("Button_leaveMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string Button_logOut {
            get {
                return ResourceManager.GetString("Button_logOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match settings.
        /// </summary>
        public static string Button_matchSettings {
            get {
                return ResourceManager.GetString("Button_matchSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Button_no {
            get {
                return ResourceManager.GetString("Button_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Button_ok {
            get {
                return ResourceManager.GetString("Button_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Button_profile {
            get {
                return ResourceManager.GetString("Button_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Button_refresh {
            get {
                return ResourceManager.GetString("Button_refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend code.
        /// </summary>
        public static string Button_resendCode {
            get {
                return ResourceManager.GetString("Button_resendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string Button_saveSettings {
            get {
                return ResourceManager.GetString("Button_saveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Button_search {
            get {
                return ResourceManager.GetString("Button_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See score breakdown.
        /// </summary>
        public static string Button_seeScores {
            get {
                return ResourceManager.GetString("Button_seeScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file.
        /// </summary>
        public static string Button_selectFile {
            get {
                return ResourceManager.GetString("Button_selectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Button_send {
            get {
                return ResourceManager.GetString("Button_send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Button_signUp {
            get {
                return ResourceManager.GetString("Button_signUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start match.
        /// </summary>
        public static string Button_startMatch {
            get {
                return ResourceManager.GetString("Button_startMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Button_update {
            get {
                return ResourceManager.GetString("Button_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View profile.
        /// </summary>
        public static string Button_viewProfile {
            get {
                return ResourceManager.GetString("Button_viewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Button_yes {
            get {
                return ResourceManager.GetString("Button_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re already logged in.
        /// </summary>
        public static string Error_alreadyLogged {
            get {
                return ResourceManager.GetString("Error_alreadyLogged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn’t send the code to your email. Try again later.
        /// </summary>
        public static string Error_codeSendFailed {
            get {
                return ResourceManager.GetString("Error_codeSendFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected connection error occurred. We’re sorry for the inconvenience.
        /// </summary>
        public static string Error_connectionEnded {
            get {
                return ResourceManager.GetString("Error_connectionEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input your username.
        /// </summary>
        public static string Error_emptyUser {
            get {
                return ResourceManager.GetString("Error_emptyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred. Please try again later.
        /// </summary>
        public static string Error_generic {
            get {
                return ResourceManager.GetString("Error_generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in all fields and try again.
        /// </summary>
        public static string Error_incompleteFields {
            get {
                return ResourceManager.GetString("Error_incompleteFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered code is wrong, try again.
        /// </summary>
        public static string Error_invalidCode {
            get {
                return ResourceManager.GetString("Error_invalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn’t log you in. Try again later.
        /// </summary>
        public static string Error_logInFailed {
            get {
                return ResourceManager.GetString("Error_logInFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your message took too long to send. Try again.
        /// </summary>
        public static string Error_messageNotSent {
            get {
                return ResourceManager.GetString("Error_messageNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results.
        /// </summary>
        public static string Error_noCoincidences {
            get {
                return ResourceManager.GetString("Error_noCoincidences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re offline. Check your Internet connection and try again.
        /// </summary>
        public static string Error_noConnection {
            get {
                return ResourceManager.GetString("Error_noConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords don’t match.
        /// </summary>
        public static string Error_passDontMatch {
            get {
                return ResourceManager.GetString("Error_passDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t update your profile data. Please try again later.
        /// </summary>
        public static string Error_profileUpdate {
            get {
                return ResourceManager.GetString("Error_profileUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t get your profile data. Try again later.
        /// </summary>
        public static string Error_retrievingData {
            get {
                return ResourceManager.GetString("Error_retrievingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password can&apos;t be the same as your current password.
        /// </summary>
        public static string Error_samePassword {
            get {
                return ResourceManager.GetString("Error_samePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn’t save your score nor update your wins and losses history. Your scores won’t change..
        /// </summary>
        public static string Error_scoresUpdFailed {
            get {
                return ResourceManager.GetString("Error_scoresUpdFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server timed out. If the problem persists, try again later.
        /// </summary>
        public static string Error_serverTimeout {
            get {
                return ResourceManager.GetString("Error_serverTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn’t create your account. Try again later.
        /// </summary>
        public static string Error_signUpFailed {
            get {
                return ResourceManager.GetString("Error_signUpFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect username or password.
        /// </summary>
        public static string Error_wrongCredentials {
            get {
                return ResourceManager.GetString("Error_wrongCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Global_lang {
            get {
                return ResourceManager.GetString("Global_lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Global_logIn {
            get {
                return ResourceManager.GetString("Global_logIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Global_password {
            get {
                return ResourceManager.GetString("Global_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Global_settings {
            get {
                return ResourceManager.GetString("Global_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Global_username {
            get {
                return ResourceManager.GetString("Global_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QWERTYUIOPASDFGHJKLZXCVBNM.
        /// </summary>
        public static string Keyboard_alphabet {
            get {
                return ResourceManager.GetString("Keyboard_alphabet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to go back? If you selected a different word, it won’t be saved.
        /// </summary>
        public static string Message_backNoSave {
            get {
                return ResourceManager.GetString("Message_backNoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you’d like to go back?.
        /// </summary>
        public static string Message_confirmGoBack {
            get {
                return ResourceManager.GetString("Message_confirmGoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to kick the player? If the match has begun, it will end.
        /// </summary>
        public static string Message_confirmKick {
            get {
                return ResourceManager.GetString("Message_confirmKick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to leave the match?.
        /// </summary>
        public static string Message_confirmLeave {
            get {
                return ResourceManager.GetString("Message_confirmLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match created successfully.
        /// </summary>
        public static string Message_creationSuccess {
            get {
                return ResourceManager.GetString("Message_creationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A verification code will be sent to the email associated with this account.
        /// </summary>
        public static string Message_emailCode {
            get {
                return ResourceManager.GetString("Message_emailCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address is already in use.
        /// </summary>
        public static string Message_emailInUse {
            get {
                return ResourceManager.GetString("Message_emailInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You’ve been kicked from the match..
        /// </summary>
        public static string Message_gotKicked {
            get {
                return ResourceManager.GetString("Message_gotKicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opponent guessed:.
        /// </summary>
        public static string Message_guessingMessage {
            get {
                return ResourceManager.GetString("Message_guessingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch out! The guessed letter is NOT in the word. Please reject it.
        /// </summary>
        public static string Message_guessIsInvalid {
            get {
                return ResourceManager.GetString("Message_guessIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! The guessed letter IS in the word. Please accept it.
        /// </summary>
        public static string Message_guessIsValid {
            get {
                return ResourceManager.GetString("Message_guessIsValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The host has left the match.
        /// </summary>
        public static string Message_hostLeft {
            get {
                return ResourceManager.GetString("Message_hostLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input code.
        /// </summary>
        public static string Message_inputCode {
            get {
                return ResourceManager.GetString("Message_inputCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You’ve kicked your opponent. For fairness, you’ve lost 3 points.
        /// </summary>
        public static string Message_kickedMidGame {
            get {
                return ResourceManager.GetString("Message_kickedMidGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You kicked {username}.
        /// </summary>
        public static string Message_kickedPlayer {
            get {
                return ResourceManager.GetString("Message_kickedPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your opponent has left the match. Your score hasn’t been affected.
        /// </summary>
        public static string Message_opponentLeft {
            get {
                return ResourceManager.GetString("Message_opponentLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! {username} didn’t guess your word. You’ve earned 5 points.
        /// </summary>
        public static string Message_opponentLost {
            get {
                return ResourceManager.GetString("Message_opponentLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {username} guessed your word. Better luck next time!.
        /// </summary>
        public static string Message_opponentWon {
            get {
                return ResourceManager.GetString("Message_opponentWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been updated.
        /// </summary>
        public static string Message_passwordUpdate {
            get {
                return ResourceManager.GetString("Message_passwordUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data has been updated.
        /// </summary>
        public static string Message_sameData {
            get {
                return ResourceManager.GetString("Message_sameData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully signed up.
        /// </summary>
        public static string Message_successSignUp {
            get {
                return ResourceManager.GetString("Message_successSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile info successfully updated.
        /// </summary>
        public static string Message_updateSuccess {
            get {
                return ResourceManager.GetString("Message_updateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to change the word?.
        /// </summary>
        public static string Message_wordChange {
            get {
                return ResourceManager.GetString("Message_wordChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! You guessed the word: {word}. You’ve earned 10 points.
        /// </summary>
        public static string Message_wordGuessed {
            get {
                return ResourceManager.GetString("Message_wordGuessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a word.
        /// </summary>
        public static string Message_wordNeeded {
            get {
                return ResourceManager.GetString("Message_wordNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too bad! You didn’t guess the word. Better luck next time!.
        /// </summary>
        public static string Message_wordNotGuessed {
            get {
                return ResourceManager.GetString("Message_wordNotGuessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You left the match..
        /// </summary>
        public static string Message_youLeft {
            get {
                return ResourceManager.GetString("Message_youLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About me.
        /// </summary>
        public static string Text_aboutMe {
            get {
                return ResourceManager.GetString("Text_aboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available matches.
        /// </summary>
        public static string Text_availableMatches {
            get {
                return ResourceManager.GetString("Text_availableMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting opponent.
        /// </summary>
        public static string Text_awaitingOpponent {
            get {
                return ResourceManager.GetString("Text_awaitingOpponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for {username} to start the match....
        /// </summary>
        public static string Text_awaitingStart {
            get {
                return ResourceManager.GetString("Text_awaitingStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animals.
        /// </summary>
        public static string Text_catAnimals {
            get {
                return ResourceManager.GetString("Text_catAnimals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        public static string Text_catColors {
            get {
                return ResourceManager.GetString("Text_catColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        public static string Text_catCountries {
            get {
                return ResourceManager.GetString("Text_catCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fruits.
        /// </summary>
        public static string Text_catFruits {
            get {
                return ResourceManager.GetString("Text_catFruits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects.
        /// </summary>
        public static string Text_catObjects {
            get {
                return ResourceManager.GetString("Text_catObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type message here….
        /// </summary>
        public static string Text_chatPrompt {
            get {
                return ResourceManager.GetString("Text_chatPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string Text_confirmPassword {
            get {
                return ResourceManager.GetString("Text_confirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created:.
        /// </summary>
        public static string Text_created {
            get {
                return ResourceManager.GetString("Text_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        public static string Text_dateOfBirth {
            get {
                return ResourceManager.GetString("Text_dateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Text_email {
            get {
                return ResourceManager.GetString("Text_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string Text_fullName {
            get {
                return ResourceManager.GetString("Text_fullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games played.
        /// </summary>
        public static string Text_gamesPlayed {
            get {
                return ResourceManager.GetString("Text_gamesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hangman.
        /// </summary>
        public static string Text_gameTitle {
            get {
                return ResourceManager.GetString("Text_gameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Text_language {
            get {
                return ResourceManager.GetString("Text_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string Text_newPassword {
            get {
                return ResourceManager.GetString("Text_newPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string Text_phone {
            get {
                return ResourceManager.GetString("Text_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {username} has joined the match.
        /// </summary>
        public static string Text_playerJoined {
            get {
                return ResourceManager.GetString("Text_playerJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {username} has left the match.
        /// </summary>
        public static string Text_playerLeft {
            get {
                return ResourceManager.GetString("Text_playerLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players:.
        /// </summary>
        public static string Text_playersInMatch {
            get {
                return ResourceManager.GetString("Text_playersInMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile picture.
        /// </summary>
        public static string Text_profilePic {
            get {
                return ResourceManager.GetString("Text_profilePic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct!.
        /// </summary>
        public static string Text_rightGuess {
            get {
                return ResourceManager.GetString("Text_rightGuess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a category.
        /// </summary>
        public static string Text_selectCategory {
            get {
                return ResourceManager.GetString("Text_selectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And a word.
        /// </summary>
        public static string Text_selectWord {
            get {
                return ResourceManager.GetString("Text_selectWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Text_today {
            get {
                return ResourceManager.GetString("Text_today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total wins.
        /// </summary>
        public static string Text_totalWins {
            get {
                return ResourceManager.GetString("Text_totalWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use system default.
        /// </summary>
        public static string Text_useSystemDefault {
            get {
                return ResourceManager.GetString("Text_useSystemDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win percentage.
        /// </summary>
        public static string Text_winPercentage {
            get {
                return ResourceManager.GetString("Text_winPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write your word.
        /// </summary>
        public static string Text_writeWord {
            get {
                return ResourceManager.GetString("Text_writeWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or write your own:.
        /// </summary>
        public static string Text_writeYourOwn {
            get {
                return ResourceManager.GetString("Text_writeYourOwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops, wrong letter! You have {attempts} attempts left.
        /// </summary>
        public static string Text_wrongGuess {
            get {
                return ResourceManager.GetString("Text_wrongGuess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You.
        /// </summary>
        public static string Text_you {
            get {
                return ResourceManager.GetString("Text_you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a match.
        /// </summary>
        public static string Title_createMatch {
            get {
                return ResourceManager.GetString("Title_createMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time to guess!.
        /// </summary>
        public static string Title_game {
            get {
                return ResourceManager.GetString("Title_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main menu.
        /// </summary>
        public static string Title_lobby {
            get {
                return ResourceManager.GetString("Title_lobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log into your account.
        /// </summary>
        public static string Title_logIn {
            get {
                return ResourceManager.GetString("Title_logIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join a match.
        /// </summary>
        public static string Title_matchesList {
            get {
                return ResourceManager.GetString("Title_matchesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match settings.
        /// </summary>
        public static string Title_matchSettings {
            get {
                return ResourceManager.GetString("Title_matchSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Title_message {
            get {
                return ResourceManager.GetString("Title_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profile.
        /// </summary>
        public static string Title_profile {
            get {
                return ResourceManager.GetString("Title_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game settings.
        /// </summary>
        public static string Title_settings {
            get {
                return ResourceManager.GetString("Title_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an account.
        /// </summary>
        public static string Title_signUp {
            get {
                return ResourceManager.GetString("Title_signUp", resourceCulture);
            }
        }
    }
}
