//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangmanGame.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HangmanGame.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Button_accept {
            get {
                return ResourceManager.GetString("Button_accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already registered?.
        /// </summary>
        public static string Button_alreadyRegistered {
            get {
                return ResourceManager.GetString("Button_alreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_cancel {
            get {
                return ResourceManager.GetString("Button_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create match.
        /// </summary>
        public static string Button_createMatch {
            get {
                return ResourceManager.GetString("Button_createMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Button_exit {
            get {
                return ResourceManager.GetString("Button_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite.
        /// </summary>
        public static string Button_invite {
            get {
                return ResourceManager.GetString("Button_invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join match.
        /// </summary>
        public static string Button_joinMatch {
            get {
                return ResourceManager.GetString("Button_joinMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string Button_logOut {
            get {
                return ResourceManager.GetString("Button_logOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Button_ok {
            get {
                return ResourceManager.GetString("Button_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string Button_reject {
            get {
                return ResourceManager.GetString("Button_reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Button_send {
            get {
                return ResourceManager.GetString("Button_send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Button_signUp {
            get {
                return ResourceManager.GetString("Button_signUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re already logged in.
        /// </summary>
        public static string Error_alreadyLogged {
            get {
                return ResourceManager.GetString("Error_alreadyLogged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input your username.
        /// </summary>
        public static string Error_emptyUser {
            get {
                return ResourceManager.GetString("Error_emptyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred. Please try again later.
        /// </summary>
        public static string Error_generic {
            get {
                return ResourceManager.GetString("Error_generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in all fields and try again.
        /// </summary>
        public static string Error_incompleteFields {
            get {
                return ResourceManager.GetString("Error_incompleteFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results.
        /// </summary>
        public static string Error_noCoincidences {
            get {
                return ResourceManager.GetString("Error_noCoincidences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re offline. Check your Internet connection and try again.
        /// </summary>
        public static string Error_noConnection {
            get {
                return ResourceManager.GetString("Error_noConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t update your profile data. Please try again later.
        /// </summary>
        public static string Error_profileUpdate {
            get {
                return ResourceManager.GetString("Error_profileUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t get your profile data. Try again later.
        /// </summary>
        public static string Error_retrievingData {
            get {
                return ResourceManager.GetString("Error_retrievingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password can&apos;t be the same as your current password.
        /// </summary>
        public static string Error_samePassword {
            get {
                return ResourceManager.GetString("Error_samePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server timed out. If the problem persists, try again later.
        /// </summary>
        public static string Error_serverConnection {
            get {
                return ResourceManager.GetString("Error_serverConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password must only have letters and/or numbers.
        /// </summary>
        public static string Error_specialCharacters {
            get {
                return ResourceManager.GetString("Error_specialCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect username or password.
        /// </summary>
        public static string Error_wrongCredentials {
            get {
                return ResourceManager.GetString("Error_wrongCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Global_lang {
            get {
                return ResourceManager.GetString("Global_lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Global_password {
            get {
                return ResourceManager.GetString("Global_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Global_settings {
            get {
                return ResourceManager.GetString("Global_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Global_signIn {
            get {
                return ResourceManager.GetString("Global_signIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Global_username {
            get {
                return ResourceManager.GetString("Global_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re already friends with this user.
        /// </summary>
        public static string Message_alreadyFriends {
            get {
                return ResourceManager.GetString("Message_alreadyFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t add yourself as a friend.
        /// </summary>
        public static string Message_isYou {
            get {
                return ResourceManager.GetString("Message_isYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string Text_confirmPassword {
            get {
                return ResourceManager.GetString("Text_confirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        public static string Text_dateOfBirth {
            get {
                return ResourceManager.GetString("Text_dateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Text_email {
            get {
                return ResourceManager.GetString("Text_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string Text_fullName {
            get {
                return ResourceManager.GetString("Text_fullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hangman.
        /// </summary>
        public static string Text_gameTitle {
            get {
                return ResourceManager.GetString("Text_gameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string Text_phone {
            get {
                return ResourceManager.GetString("Text_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Title_message {
            get {
                return ResourceManager.GetString("Title_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log into your account.
        /// </summary>
        public static string Title_signIn {
            get {
                return ResourceManager.GetString("Title_signIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an account.
        /// </summary>
        public static string Title_signUp {
            get {
                return ResourceManager.GetString("Title_signUp", resourceCulture);
            }
        }
    }
}
