//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangmanGame.Client.HangmanGameService {

    // ============= AUTH SERVICE =============
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HangmanGameService.IAuthService")]
    public interface IAuthService {

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/Register", ReplyAction="http://tempuri.org/IAuthService/RegisterResponse")]
        HangmanGame.Core.Core.DTOs.RegisterResponseDto Register(HangmanGame.Core.Core.DTOs.RegisterRequestDto request);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/Register", ReplyAction="http://tempuri.org/IAuthService/RegisterResponse")]
        System.Threading.Tasks.Task<HangmanGame.Core.Core.DTOs.RegisterResponseDto> RegisterAsync(HangmanGame.Core.Core.DTOs.RegisterRequestDto request);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/SignIn", ReplyAction="http://tempuri.org/IAuthService/SignInResponse")]
        HangmanGame.Core.Core.DTOs.SignInResponseDto SignIn(HangmanGame.Core.Core.DTOs.SignInRequestDto request);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/SignIn", ReplyAction="http://tempuri.org/IAuthService/SignInResponse")]
        System.Threading.Tasks.Task<HangmanGame.Core.Core.DTOs.SignInResponseDto> SignInAsync(HangmanGame.Core.Core.DTOs.SignInRequestDto request);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthServiceChannel : HangmanGame.Client.HangmanGameService.IAuthService, System.ServiceModel.IClientChannel {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthServiceClient : System.ServiceModel.ClientBase<HangmanGame.Client.HangmanGameService.IAuthService>, HangmanGame.Client.HangmanGameService.IAuthService {

        public AuthServiceClient() {
        }

        public AuthServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }

        public AuthServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }

        public AuthServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }

        public AuthServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }

        public HangmanGame.Core.Core.DTOs.RegisterResponseDto Register(HangmanGame.Core.Core.DTOs.RegisterRequestDto request) {
            return base.Channel.Register(request);
        }

        public System.Threading.Tasks.Task<HangmanGame.Core.Core.DTOs.RegisterResponseDto> RegisterAsync(HangmanGame.Core.Core.DTOs.RegisterRequestDto request) {
            return base.Channel.RegisterAsync(request);
        }

        public HangmanGame.Core.Core.DTOs.SignInResponseDto SignIn(HangmanGame.Core.Core.DTOs.SignInRequestDto request) {
            return base.Channel.SignIn(request);
        }

        public System.Threading.Tasks.Task<HangmanGame.Core.Core.DTOs.SignInResponseDto> SignInAsync(HangmanGame.Core.Core.DTOs.SignInRequestDto request) {
            return base.Channel.SignInAsync(request);
        }
    }

    // ============= USER SERVICE =============
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HangmanGameService.IUserService")]
    public interface IUserService {

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/LoadProfile", ReplyAction="http://tempuri.org/IUserService/LoadProfileResponse")]
        HangmanGame.Core.Core.DTOs.ProfileResponseDto LoadProfile(HangmanGame.Core.Core.DTOs.LoadProfileRequestDto request);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/LoadProfile", ReplyAction="http://tempuri.org/IUserService/LoadProfileResponse")]
        System.Threading.Tasks.Task<HangmanGame.Core.Core.DTOs.ProfileResponseDto> LoadProfileAsync(HangmanGame.Core.Core.DTOs.LoadProfileRequestDto request);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : HangmanGame.Client.HangmanGameService.IUserService, System.ServiceModel.IClientChannel {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<HangmanGame.Client.HangmanGameService.IUserService>, HangmanGame.Client.HangmanGameService.IUserService {

        public UserServiceClient() {
        }

        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }

        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }

        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }

        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }

        public HangmanGame.Core.Core.DTOs.ProfileResponseDto LoadProfile(HangmanGame.Core.Core.DTOs.LoadProfileRequestDto request) {
            return base.Channel.LoadProfile(request);
        }

        public System.Threading.Tasks.Task<HangmanGame.Core.Core.DTOs.ProfileResponseDto> LoadProfileAsync(HangmanGame.Core.Core.DTOs.LoadProfileRequestDto request) {
            return base.Channel.LoadProfileAsync(request);
        }
    }

    // ============= WORD SERVICE =============
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HangmanGameService.IWordService")]
    public interface IWordService {

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordService/GetWords", ReplyAction="http://tempuri.org/IWordService/GetWordsResponse")]
        HangmanGame.Core.Core.DTOs.WordResponseDto GetWords(HangmanGame.Core.Core.DTOs.WordRequestDto request);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordService/GetWords", ReplyAction="http://tempuri.org/IWordService/GetWordsResponse")]
        System.Threading.Tasks.Task<HangmanGame.Core.Core.DTOs.WordResponseDto> GetWordsAsync(HangmanGame.Core.Core.DTOs.WordRequestDto request);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWordServiceChannel : HangmanGame.Client.HangmanGameService.IWordService, System.ServiceModel.IClientChannel {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WordServiceClient : System.ServiceModel.ClientBase<HangmanGame.Client.HangmanGameService.IWordService>, HangmanGame.Client.HangmanGameService.IWordService {

        public WordServiceClient() {
        }

        public WordServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }

        public WordServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }

        public WordServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }

        public WordServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }

        public HangmanGame.Core.Core.DTOs.WordResponseDto GetWords(HangmanGame.Core.Core.DTOs.WordRequestDto request) {
            return base.Channel.GetWords(request);
        }

        public System.Threading.Tasks.Task<HangmanGame.Core.Core.DTOs.WordResponseDto> GetWordsAsync(HangmanGame.Core.Core.DTOs.WordRequestDto request) {
            return base.Channel.GetWordsAsync(request);
        }
    }

    // ============= MATCH SERVICE =============
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HangmanGameService.IMatchService")]
    public interface IMatchService {

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/GetAvailableMatches", ReplyAction="http://tempuri.org/IMatchService/GetAvailableMatchesResponse")]
        HangmanGame.Core.Core.DTOs.GetAvailableMatchesResponseDto GetAvailableMatches(HangmanGame.Core.Core.DTOs.GetAvailableMatchesRequestDto request);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/GetAvailableMatches", ReplyAction="http://tempuri.org/IMatchService/GetAvailableMatchesResponse")]
        System.Threading.Tasks.Task<HangmanGame.Core.Core.DTOs.GetAvailableMatchesResponseDto> GetAvailableMatchesAsync(HangmanGame.Core.Core.DTOs.GetAvailableMatchesRequestDto request);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMatchServiceChannel : HangmanGame.Client.HangmanGameService.IMatchService, System.ServiceModel.IClientChannel {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MatchServiceClient : System.ServiceModel.ClientBase<HangmanGame.Client.HangmanGameService.IMatchService>, HangmanGame.Client.HangmanGameService.IMatchService {

        public MatchServiceClient() {
        }

        public MatchServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }

        public MatchServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }

        public MatchServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }

        public MatchServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }

        public HangmanGame.Core.Core.DTOs.GetAvailableMatchesResponseDto GetAvailableMatches(HangmanGame.Core.Core.DTOs.GetAvailableMatchesRequestDto request) {
            return base.Channel.GetAvailableMatches(request);
        }

        public System.Threading.Tasks.Task<HangmanGame.Core.Core.DTOs.GetAvailableMatchesResponseDto> GetAvailableMatchesAsync(HangmanGame.Core.Core.DTOs.GetAvailableMatchesRequestDto request) {
            return base.Channel.GetAvailableMatchesAsync(request);
        }
    }
}