//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangmanGame.Client.HangmanGameService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HangmanGameService.IAuthService")]
    public interface IAuthService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/Register", ReplyAction="http://tempuri.org/IAuthService/RegisterResponse")]
        HangmanGame.Core.Core.DTOs.RegisterResponseDto Register(HangmanGame.Core.Core.DTOs.RegisterRequestDto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/Register", ReplyAction="http://tempuri.org/IAuthService/RegisterResponse")]
        System.Threading.Tasks.Task<HangmanGame.Core.Core.DTOs.RegisterResponseDto> RegisterAsync(HangmanGame.Core.Core.DTOs.RegisterRequestDto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/SignIn", ReplyAction="http://tempuri.org/IAuthService/SignInResponse")]
        HangmanGame.Core.Core.DTOs.SignInResponseDto SignIn(HangmanGame.Core.Core.DTOs.SignInRequestDto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/SignIn", ReplyAction="http://tempuri.org/IAuthService/SignInResponse")]
        System.Threading.Tasks.Task<HangmanGame.Core.Core.DTOs.SignInResponseDto> SignInAsync(HangmanGame.Core.Core.DTOs.SignInRequestDto request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthServiceChannel : HangmanGame.Client.HangmanGameService.IAuthService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthServiceClient : System.ServiceModel.ClientBase<HangmanGame.Client.HangmanGameService.IAuthService>, HangmanGame.Client.HangmanGameService.IAuthService {
        
        public AuthServiceClient() {
        }
        
        public AuthServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HangmanGame.Core.Core.DTOs.RegisterResponseDto Register(HangmanGame.Core.Core.DTOs.RegisterRequestDto request) {
            return base.Channel.Register(request);
        }
        
        public System.Threading.Tasks.Task<HangmanGame.Core.Core.DTOs.RegisterResponseDto> RegisterAsync(HangmanGame.Core.Core.DTOs.RegisterRequestDto request) {
            return base.Channel.RegisterAsync(request);
        }
        
        public HangmanGame.Core.Core.DTOs.SignInResponseDto SignIn(HangmanGame.Core.Core.DTOs.SignInRequestDto request) {
            return base.Channel.SignIn(request);
        }
        
        public System.Threading.Tasks.Task<HangmanGame.Core.Core.DTOs.SignInResponseDto> SignInAsync(HangmanGame.Core.Core.DTOs.SignInRequestDto request) {
            return base.Channel.SignInAsync(request);
        }
    }
}
